---

- name: count hosts in play
  hosts: all
  connection: local
  gather_facts: false
  tasks:
  - debug:
      msg: There are {{ ansible_play_hosts | length }} hosts in this play
    run_once: true
