---

- hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    hostname: server.pat.demolab.local
    domain: demolab.local
  tasks:
  - debug: 
      msg: domain is {{ hostname.split('.', 1)[1] }}

  - debug: 
      msg: hostname is {{ hostname.split('.')[:-2] | join('.') }}
