---

- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vrfs:
      - vrf1
      - vrf2
      - vrf3
    routes:
      - 1.1.1.1
      - 2.2.2.2
      - 3.3.3.3

  tasks:
  - name: print combination of routes and vrfs
    debug: 
      msg: "vrf is {{ item.0 }} and route is {{ item.1 }}"
    loop: "{{ vrfs | product(routes)|list }}"
