---

- name: install nginx
  yum:
    name: nginx
    state: installed

- name: get certbot
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: "{{ ansible_user_dir }}"
    mode: 0755
  when: 
    - generate_letsencypt_certs
    - manage_certs

- name: get cert from letsencrypt
  command: "{{ ansible_user_dir }}/certbot-auto certonly --standalone -d {{ rocket_url }} --email {{ letsencrypt_email }} -n --agree-tos"
  register: issue_cert
  until: issue_cert is not failed
  retries: 5
  changed_when: "'Certificate not yet due for renewal' not in issue_cert.stdout"
  when:
    - generate_letsencypt_certs
    - manage_certs
  
- name: copy ssl key and cert in place
  copy:
     remote_src: true
     src: "/etc/letsencrypt/live/{{ rocket_url }}/{{ item.src_file }}"
     dest: "{{ item.dest_file }}"
  loop:
    - { "src_file": "fullchain.pem", "dest_file": "/etc/nginx/certificate.crt" }
    - { "src_file": "privkey.pem", "dest_file": "/etc/nginx/certificate.key" }
  when:
    - generate_letsencypt_certs
    - manage_certs

- name: template out ngnix config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: restart nginx

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
