---

- name: gather service facts
  service_facts:

- name: stop automation controller
  service: 
    name: automation-controller.service
    state: stopped
  become: true
  when: '"automation-controller.service" in ansible_facts.services'
