---

- name: gather service facts
  service_facts:

- name: stop tower
  service: 
    name: ansible-tower.service
    state: stopped
  become: true
  when: '"ansible-tower.service" in ansible_facts.services'
