---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        manage_certs: false
        generate_letsencypt_certs: false
        rocket_url: rocket.example.com
verifier:
  name: ansible
lint: ansible-lint 
