name: molecule
on: [push]
jobs:
  ansible-molecule:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v2
      - name: configure molecule
        run: | 
          sudo apt-get -y update
          python3 -m venv ~/ansible_molecule
          ~/ansible_molecule/bin/pip3 install pip --upgrade
          ~/ansible_molecule/bin/pip3 install molecule[docker] molecule[docker] cryptography
          source ~/ansible_molecule/bin/activate
      - name: run molecule against roles
        run: |
          for i in $(ls -d roles/*/) ; do cd $i ; molecule test ; cd ../.. ; done
      - name: run molecule against playbook
        run: |
          cd $GITHUB_WORKSPACE
          molecule test
